#端口号
server:
  port: 8088

#MyBatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jasypt mysql加密
#jasypt:
#  encryptor:
#    password: !@@@@@@

#datasource
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(LSDy1/GxmFxLvLfwQp6ckMrbRd0mBeSvj3LssCYXcFQg+iMbsrLuE1ZxnW6lX65yKOwt7I4ujFhpsB3eAdrutGjQN/HKNMnhiILJktybRuo+v8iqhmmdrIfClvGg9aeOpkhZ9UusbkFhap/iTzLhOg==)
#    username: ENC(DSWqvRVYv86prm6jvAa7zw==)
#    password: ENC(ZarMcE8xJqPDgIyIeq9+X9BBkGLBvcC8)
#    redis
  redis:
    port: 6379
    host: 43.138.34.132
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true
      cache-null-values: true



#   榛子云配置

sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 111403
  appSecret: 6088b183-73e0-4bce-805b-33ca0e8e3da8
  timeOut: 3
  codeLength: 6


jwt:  #jwt配置，供JWTUtils类使用
  key: kangkang  #jwt生成token时的密钥
  expiration: 5000  #token 5秒超时

##榛子云短信配置
#zhenzi:
#  apiUrl: https://sms_developer.zhenzikj.com #注意区别个人用户和企业用户
#  appId: 111403
#  appSecret: 6088b183-73e0-4bce-805b-33ca0e8e3da8
#  templateId: 1 #模板id
#  invalidTimer: 1 #失效时间1分钟（提示）